services:
  api:
    image: infrared_marble-api:prod
    platform: linux/amd64
    volumes:
      - ${DATA_DIR:-./data}:/app/data
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - REDIS_URL=redis://redis:6379/0
      - BLACKMARBLE_TOKEN==== REDACTED $BLACKMARBLE_TOKEN ===

  web:
    image: infrared_marble-web:prod
    build:
      context: ./web
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000 # Needs to be set at build-time
    ports:
      - 3000:3000
    environment:
      - API_URL=http://api:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
