services:
  api:
    image: infrared_marble-api:prod
    platform: linux/amd64
    volumes:
      - ./data:/app/data
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - REDIS_URL=redis://redis:6379/0
      - BLACKMARBLE_TOKEN==== REDACTED $BLACKMARBLE_TOKEN ===
    depends_on:
      redis:
        condition: service_healthy

  web:
    image: infrared_marble-web:prod
    build:
      context: ./web
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000 # Needs to be set at build-time
    ports:
      - 3000:3000
    environment:
      - API_URL=http://api:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
