services:
  api:
    image: fedemanto/infrared-marble-api:latest
    platform: linux/amd64
    volumes:
      - ${DATA_DIR:-./data}:/app/data
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - BLACKMARBLE_TOKEN=${BLACKMARBLE_TOKEN:-=== REDACTED $BLACKMARBLE_TOKEN ===}

  web:
    image: fedemanto/infrared-marble-web:latest
    build:
      context: ./web
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000 # Needs to be set at build-time
    ports:
      - 3000:3000
    environment:
      - API_URL=http://api:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
