# Conda environment for the AI4Good Satellite Overpass Times project.
#
# This file includes necessary dependencies, as well as some environment
# variables that should be set for the code to run.
#
# If you want to add a new dependency, don't forget to add it to this file too.
name: infrared-marble
variables:
  # Black Marble profile Bearer token. This token expires on 2025-05-20. When
  # that happens, you need to re-generate one with the account info provided in
  # the README.
  BLACKMARBLE_TOKEN: "=== REDACTED $BLACKMARBLE_TOKEN ==="
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - ipykernel
      - notebook
      - folium
      - matplotlib
      - mapclassify
      - -e ./blackmarblepy
      - colorcet
      # - blackmarblepy
      # Since blackmarbelpy currently has a bug in how downloads are handled, we cannot directy use
      # the pip version. Thus we forke the blackmarblepy repo, and install it as an editable local
      # dependency with pip install -e ./blackmarblepy. The git submodule should be set up to point
      # to the correct patched commit.
