# Conda environment for the AI4Good Satellite Overpass Times project.
#
# This file includes necessary dependencies, as well as some environment
# variables that should be set for the code to run.
#
# If you want to add a new dependency, don't forget to add it to this file too.
name: infrared-marble
variables:
  # Black Marble profile Bearer token. Generate one on https://urs.earthdata.nasa.gov/profile, and give access to the
  # following applications:
  #
  # - LAADS DAAC Cumulus (PROD)
  # - LAADS Web
  # - NASA GESDISC DATA ARCHIVE
  #
  # Then proceed to creating the envrionment with conda. Note to mamba users: mamba does not support environment
  # variables, set them in your rc files or $CONDA_PREFIX/etc/conda/activate.d
  BLACKMARBLE_TOKEN: "=== REDACTED $BLACKMARBLE_TOKEN ==="
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - gdal
  - numcodecs
  - pip:
      # requirements.txt holds packages shared by interactive installation (conda) and Docker install (for API)
      # Do NOT put unnecessary packages like jupyter-notebook in requirements.txt, as this just increases the Docker
      # image size. You can still include them in this environment file.
      - -r requirements.txt
      - -r requirements.dev.txt
      # Install this separately as Dockerfile needs to install this in stages
      - -e ./blackmarblepy
