# Conda environment for the AI4Good Satellite Overpass Times project.
#
# This file includes necessary dependencies, as well as some environment
# variables that should be set for the code to run.
#
# If you want to add a new dependency, don't forget to add it to this file too.
name: infrared-marble
variables:
  # Black Marble profile Bearer token. This token expires on 2025-05-20. When
  # that happens, you need to re-generate one with the account info provided in
  # the README.
  BLACKMARBLE_TOKEN: "=== REDACTED $BLACKMARBLE_TOKEN ==="
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      # requirements.txt holds packages shared by interactive installation (conda) and Docker install (for API)
      # Do NOT put unnecessary packages like jupyter-notebook in requirements.txt, as this just increases the Docker
      # image size. You can still include them in this environment file.
      - -r requirements.txt
      - ipykernel
      - ipywidgets
      - notebook
      # Install this separately as Dockerfile needs to install this in stages
      - -e ./blackmarblepy
