# Conda environment for the AI4Good Satellite Overpass Times project.
#
# This file includes necessary dependencies, as well as some environment
# variables that should be set for the code to run.
#
# If you want to add a new dependency, don't forget to add it to this file too.
name: infrared-marble
variables:
  # Black Marble profile Bearer token. This token expires on 2025-05-20. When
  # that happens, you need to re-generate one with the account info provided in
  # the README.
  BLACKMARBLE_TOKEN: "eyJ0eXAiOiJKV1QiLCJvcmlnaW4iOiJFYXJ0aGRhdGEgTG9naW4iLCJzaWciOiJlZGxqd3RwdWJrZXlfb3BzIiwiYWxnIjoiUlMyNTYifQ.eyJ0eXBlIjoiVXNlciIsInVpZCI6ImFpNGdvb2RfYmxhY2ttYXJibGUiLCJleHAiOjE3NTIxNDQ0NTIsImlhdCI6MTc0Njk2MDQ1MiwiaXNzIjoiaHR0cHM6Ly91cnMuZWFydGhkYXRhLm5hc2EuZ292IiwiaWRlbnRpdHlfcHJvdmlkZXIiOiJlZGxfb3BzIiwiYWNyIjoiZWRsIiwiYXNzdXJhbmNlX2xldmVsIjozfQ.6za3jfcl5vtVIuFTpPLQiHQIdQRFDG2n94eeKAhG6W86ZNL1KWz2OwpzqLjensvQXpzHFVXMO2kfCm9t_U3cpW0S8tvm5TS4dmtpbkuC-pOHrPiNkcJPi_yikJ1qhwbmmP_dUMYlAMzvxEZcEKBGh96zABVUvtuvu07xHccIgYe3T8_Pg4j62qHcWYYqI9AOIjhCu89_1kNN1JkUtFEuJzlAlK_4anWhNzBmowSgjs-SiLgyNFGii4n9AJl4TTw_ZdOWJJ0ueux8_w18Zn9-MeQ45Duz8aNh0ZKy4sPF79ChjzVgj4tZCnhnMvjUcJa_ZeLYvXeYaHzq0uHHnQ3ObQ"
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - gdal
  - numcodecs
  - pip:
      # requirements.txt holds packages shared by interactive installation (conda) and Docker install (for API)
      # Do NOT put unnecessary packages like jupyter-notebook in requirements.txt, as this just increases the Docker
      # image size. You can still include them in this environment file.
      - -r requirements.txt
      - -r requirements.dev.txt
      - ipykernel
      - ipywidgets
      - notebook
      # Install this separately as Dockerfile needs to install this in stages
      - -e ./blackmarblepy
